goog.module('org.patternfly.component.textinputgroup.BaseFilterInput');

goog.require('elemental2.dom.Event.$Overlay');
goog.require('java.lang.Boolean');
goog.require('java.lang.String');
goog.require('java.util.ArrayList');
goog.require('java.util.List');
goog.require('java.util.function.BiConsumer');
goog.require('java.util.function.BiFunction');
goog.require('java.util.function.Consumer');
goog.require('java.util.function.Function');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.Id');
goog.require('org.jboss.elemento.Key');
goog.require('org.patternfly.component.AddItemHandler');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.RemoveItemHandler');
goog.require('org.patternfly.component.label.Label');
goog.require('org.patternfly.component.label.LabelGroup');
goog.require('org.patternfly.component.textinputgroup.BaseSearchInput');
goog.require('org.patternfly.component.textinputgroup.BaseTextInputGroup');
goog.require('org.patternfly.handler.ChangeHandler');
goog.require('org.patternfly.handler.ComponentHandler');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const BaseFilterInput = goog.require('org.patternfly.component.textinputgroup.BaseFilterInput$impl');
exports = BaseFilterInput;
