goog.module('org.patternfly.component.page.PageMain');

goog.require('elemental2.dom.AddEventListenerOptions.$Overlay');
goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('elemental2.dom.Node.$Overlay');
goog.require('elemental2.dom.TouchEvent.$Overlay');
goog.require('java.lang.Iterable');
goog.require('java.lang.String');
goog.require('java.util.function.Supplier');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.ElementContainerDelegate');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.IsElement');
goog.require('org.patternfly.component.page.Page');
goog.require('org.patternfly.component.page.PageGroup');
goog.require('org.patternfly.component.page.PageSectionLike');
goog.require('org.patternfly.component.page.PageSubComponent');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.core.Roles');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Modifiers.Fill');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const PageMain = goog.require('org.patternfly.component.page.PageMain$impl');
exports = PageMain;
