goog.module('org.patternfly.component.popover.Popover');

goog.require('elemental2.dom.DomGlobal.$Overlay');
goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('elemental2.dom.MutationRecord.$Overlay');
goog.require('java.lang.String');
goog.require('java.util.ArrayList');
goog.require('java.util.List');
goog.require('java.util.function.Supplier');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Attachable');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.Id');
goog.require('org.patternfly.component.BaseComponent');
goog.require('org.patternfly.component.Closeable');
goog.require('org.patternfly.component.ComponentIcon');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.Severity');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.component.popover.PopoverBody');
goog.require('org.patternfly.component.popover.PopoverFooter');
goog.require('org.patternfly.component.popover.PopoverHeader');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.core.Roles');
goog.require('org.patternfly.handler.CloseHandler');
goog.require('org.patternfly.handler.OverlayHandler');
goog.require('org.patternfly.icon.IconSets.rhMicrons');
goog.require('org.patternfly.icon.PredefinedIcon');
goog.require('org.patternfly.overlay.CssPositioning');
goog.require('org.patternfly.overlay.Overlay');
goog.require('org.patternfly.overlay.TriggerMode');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Modifiers.NoPadding');
goog.require('org.patternfly.style.Placement');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const Popover = goog.require('org.patternfly.component.popover.Popover$impl');
exports = Popover;
