goog.module('org.patternfly.component.progressstepper.ProgressStepper');

goog.require('elemental2.dom.HTMLLIElement.$Overlay');
goog.require('elemental2.dom.HTMLOListElement.$Overlay');
goog.require('java.lang.Class');
goog.require('java.lang.Integer');
goog.require('java.lang.Iterable');
goog.require('java.lang.String');
goog.require('java.util.ArrayList');
goog.require('java.util.Iterator');
goog.require('java.util.LinkedHashMap');
goog.require('java.util.List');
goog.require('java.util.Map');
goog.require('java.util.Optional');
goog.require('java.util.Spliterator');
goog.require('java.util.function.BiConsumer');
goog.require('java.util.function.Consumer');
goog.require('java.util.function.Function');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.logger.Logger');
goog.require('org.patternfly.component.AddItemHandler');
goog.require('org.patternfly.component.AurHandler');
goog.require('org.patternfly.component.BaseComponent');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.HasItems');
goog.require('org.patternfly.component.RemoveItemHandler');
goog.require('org.patternfly.component.UpdateItemHandler');
goog.require('org.patternfly.component.progressstepper.ProgressStep');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.core.Roles');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Modifiers.Center');
goog.require('org.patternfly.style.Modifiers.Compact');
goog.require('org.patternfly.style.Modifiers.Vertical');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const ProgressStepper = goog.require('org.patternfly.component.progressstepper.ProgressStepper$impl');
exports = ProgressStepper;
