goog.module('org.patternfly.showcase.component.ButtonComponent');

goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('java.lang.Class');
goog.require('java.lang.String');
goog.require('java.util.function.Supplier');
goog.require('jsinterop.base.JsPropertyMap.$Overlay');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.IconPosition');
goog.require('org.patternfly.component.badge.Badge');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.handler.ComponentHandler');
goog.require('org.patternfly.icon.IconSets.fas');
goog.require('org.patternfly.icon.IconSets.rhMicrons');
goog.require('org.patternfly.icon.IconSets.rhUi');
goog.require('org.patternfly.layout.flex.Flex');
goog.require('org.patternfly.layout.flex.Gap');
goog.require('org.patternfly.showcase.ApiDoc.Type');
goog.require('org.patternfly.showcase.Code');
goog.require('org.patternfly.showcase.Data');
goog.require('org.patternfly.showcase.Snippet');
goog.require('org.patternfly.showcase.SnippetPage');
goog.require('org.patternfly.showcase.component.Component.$Overlay');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.NotificationStatus');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const ButtonComponent = goog.require('org.patternfly.showcase.component.ButtonComponent$impl');
exports = ButtonComponent;
