goog.module('org.patternfly.component.tooltip.Tooltip');

goog.require('elemental2.dom.DomGlobal.$Overlay');
goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.MutationRecord.$Overlay');
goog.require('elemental2.dom.Node.$Overlay');
goog.require('java.lang.String');
goog.require('java.util.ArrayList');
goog.require('java.util.List');
goog.require('java.util.function.Supplier');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Attachable');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.ElementContainerDelegate');
goog.require('org.jboss.elemento.ElementTextDelegate');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.Id');
goog.require('org.patternfly.component.BaseComponent');
goog.require('org.patternfly.component.Closeable');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.tooltip.TriggerAria');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.core.Roles');
goog.require('org.patternfly.handler.CloseHandler');
goog.require('org.patternfly.handler.OverlayHandler');
goog.require('org.patternfly.overlay.CssPositioning');
goog.require('org.patternfly.overlay.Overlay');
goog.require('org.patternfly.overlay.TriggerMode');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Placement');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const Tooltip = goog.require('org.patternfly.component.tooltip.Tooltip$impl');
exports = Tooltip;
