goog.module('org.patternfly.component.ComponentStore');

goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.MutationRecord.$Overlay');
goog.require('java.lang.Class');
goog.require('java.lang.Exception');
goog.require('java.lang.Object');
goog.require('java.lang.String');
goog.require('java.util.HashMap');
goog.require('java.util.Map');
goog.require('java.util.function.Function');
goog.require('javaemul.internal.Exceptions');
goog.require('jsinterop.base.JsPropertyMap.$Overlay');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.Id');
goog.require('org.jboss.elemento.ObserverCallback');
goog.require('org.jboss.elemento.TypedBuilder');
goog.require('org.jboss.elemento.logger.Level');
goog.require('org.jboss.elemento.logger.Logger');
goog.require('org.patternfly.component.BaseComponent');
goog.require('org.patternfly.component.ComponentDelegate');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.SubComponent');
goog.require('vmbootstrap.Casts');

const ComponentStore = goog.require('org.patternfly.component.ComponentStore$impl');
exports = ComponentStore;
