goog.module('org.patternfly.component.SubComponent');

goog.require('elemental2.dom.AddEventListenerOptions.$Overlay');
goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.EventTarget.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.Node.$Overlay');
goog.require('java.lang.Iterable');
goog.require('java.lang.Object');
goog.require('java.lang.String');
goog.require('java.util.Objects');
goog.require('java.util.function.Consumer');
goog.require('java.util.function.Supplier');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.ClassList');
goog.require('org.jboss.elemento.ElementAttributeMethods');
goog.require('org.jboss.elemento.ElementClassListMethods');
goog.require('org.jboss.elemento.ElementConsumerMethods');
goog.require('org.jboss.elemento.ElementContainerMethods');
goog.require('org.jboss.elemento.ElementEventMethods');
goog.require('org.jboss.elemento.ElementIdMethods');
goog.require('org.jboss.elemento.ElementQueryMethods');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLElementAttributeMethods');
goog.require('org.jboss.elemento.HTMLElementDataMethods');
goog.require('org.jboss.elemento.HTMLElementStyleMethods');
goog.require('org.jboss.elemento.HTMLElementVisibilityMethods');
goog.require('org.jboss.elemento.Id');
goog.require('org.jboss.elemento.IsElement');
goog.require('org.jboss.elemento.Role');
goog.require('org.jboss.elemento.TypedBuilder');
goog.require('org.patternfly.component.BaseComponent');
goog.require('org.patternfly.component.ComponentDelegate');
goog.require('org.patternfly.component.ComponentRegistry');
goog.require('org.patternfly.component.ComponentStore');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.core.OuiaSupport');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const SubComponent = goog.require('org.patternfly.component.SubComponent$impl');
exports = SubComponent;
