goog.module('org.patternfly.component.togglegroup.ToggleGroupItem');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLButtonElement.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('elemental2.dom.Node.$Overlay');
goog.require('java.lang.Boolean');
goog.require('java.lang.String');
goog.require('java.util.HashMap');
goog.require('java.util.Map');
goog.require('java.util.function.Supplier');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.ButtonType');
goog.require('org.jboss.elemento.ElementContainerDelegate');
goog.require('org.jboss.elemento.ElementTextMethods');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.ComponentIcon');
goog.require('org.patternfly.component.ComponentIconAndText');
goog.require('org.patternfly.component.HasIdentifier');
goog.require('org.patternfly.component.IconPosition');
goog.require('org.patternfly.component.SelectionMode');
goog.require('org.patternfly.component.togglegroup.ToggleGroup');
goog.require('org.patternfly.component.togglegroup.ToggleGroupSubComponent');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.ComponentContext');
goog.require('org.patternfly.core.Dataset');
goog.require('org.patternfly.handler.ComponentHandler');
goog.require('org.patternfly.icon.PredefinedIcon');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Modifiers.Disabled');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const ToggleGroupItem = goog.require('org.patternfly.component.togglegroup.ToggleGroupItem$impl');
exports = ToggleGroupItem;
