goog.module('org.patternfly.component.numberinput.NumberInput');

goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.FocusEvent.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.KeyboardEvent.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('java.lang.Double');
goog.require('java.lang.NumberFormatException');
goog.require('java.lang.String');
goog.require('java.util.LinkedList');
goog.require('java.util.List');
goog.require('java.util.Objects');
goog.require('java.util.function.Consumer');
goog.require('java.util.function.UnaryOperator');
goog.require('javaemul.internal.Exceptions');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.Id');
goog.require('org.jboss.elemento.Key');
goog.require('org.patternfly.component.BaseComponent');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.HasValue');
goog.require('org.patternfly.component.ValidationStatus');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.component.form.TextInput');
goog.require('org.patternfly.component.form.TextInputType');
goog.require('org.patternfly.component.inputgroup.InputGroup');
goog.require('org.patternfly.component.inputgroup.InputGroupItem');
goog.require('org.patternfly.component.numberinput.UnitPosition');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.handler.ChangeHandler');
goog.require('org.patternfly.icon.IconSets.fas');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Modifiers.Disabled');
goog.require('org.patternfly.style.Variable');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const NumberInput = goog.require('org.patternfly.component.numberinput.NumberInput$impl');
exports = NumberInput;
