goog.module('org.patternfly.component.form.Form');

goog.require('elemental2.dom.HTMLFormElement.$Overlay');
goog.require('java.lang.Iterable');
goog.require('java.lang.String');
goog.require('java.util.ArrayList');
goog.require('java.util.Iterator');
goog.require('java.util.LinkedHashMap');
goog.require('java.util.List');
goog.require('java.util.Map');
goog.require('java.util.Spliterator');
goog.require('java.util.function.BiConsumer');
goog.require('java.util.function.Consumer');
goog.require('java.util.function.Function');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.AddItemHandler');
goog.require('org.patternfly.component.AurHandler');
goog.require('org.patternfly.component.BaseComponent');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.HasItems');
goog.require('org.patternfly.component.RemoveItemHandler');
goog.require('org.patternfly.component.UpdateItemHandler');
goog.require('org.patternfly.component.alert.Alert');
goog.require('org.patternfly.component.form.FormActionGroup');
goog.require('org.patternfly.component.form.FormAlert');
goog.require('org.patternfly.component.form.FormFieldGroup');
goog.require('org.patternfly.component.form.FormGroup');
goog.require('org.patternfly.component.form.FormSection');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Modifiers.Horizontal');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const Form = goog.require('org.patternfly.component.form.Form$impl');
exports = Form;
