goog.module('org.patternfly.component.progress.Progress');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('java.lang.Integer');
goog.require('java.lang.String');
goog.require('java.util.ArrayList');
goog.require('java.util.List');
goog.require('java.util.function.Consumer');
goog.require('javaemul.internal.primitives.$int');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.Id');
goog.require('org.patternfly.component.BaseComponent');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.HasValue');
goog.require('org.patternfly.component.ValidationStatus');
goog.require('org.patternfly.component.help.HelperText');
goog.require('org.patternfly.component.progress.MeasureLocation');
goog.require('org.patternfly.component.progress.ProgressLabel');
goog.require('org.patternfly.component.tooltip.Tooltip');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.core.Numbers');
goog.require('org.patternfly.core.ObservableValue');
goog.require('org.patternfly.core.ObservableValue.Subscriber');
goog.require('org.patternfly.core.Roles');
goog.require('org.patternfly.core.Validation');
goog.require('org.patternfly.handler.ChangeHandler');
goog.require('org.patternfly.icon.IconSets.rhUi');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Size');
goog.require('org.patternfly.style.Status');
goog.require('org.patternfly.style.TypedModifier');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const Progress = goog.require('org.patternfly.component.progress.Progress$impl');
exports = Progress;
