goog.module('org.patternfly.component.table.Table');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLInputElement.$Overlay');
goog.require('elemental2.dom.HTMLTableCellElement.$Overlay');
goog.require('elemental2.dom.HTMLTableElement.$Overlay');
goog.require('elemental2.dom.HTMLTableRowElement.$Overlay');
goog.require('elemental2.dom.HTMLTableSectionElement.$Overlay');
goog.require('elemental2.dom.MutationRecord.$Overlay');
goog.require('java.lang.String');
goog.require('java.util.ArrayList');
goog.require('java.util.Collections');
goog.require('java.util.List');
goog.require('java.util.function.Consumer');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Attachable');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.BaseComponent');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.SelectionMode');
goog.require('org.patternfly.component.table.TableCaption');
goog.require('org.patternfly.component.table.TableType');
goog.require('org.patternfly.component.table.Tbody');
goog.require('org.patternfly.component.table.Th');
goog.require('org.patternfly.component.table.Thead');
goog.require('org.patternfly.component.table.Tr');
goog.require('org.patternfly.component.table.TreeViewGridBreakpoint');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.core.Roles');
goog.require('org.patternfly.core.Validation');
goog.require('org.patternfly.handler.MultiSelectHandler');
goog.require('org.patternfly.handler.SelectHandler');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.GridBreakpoint');
goog.require('org.patternfly.style.Modifiers');
goog.require('org.patternfly.style.Modifiers.Compact');
goog.require('org.patternfly.style.Modifiers.Plain');
goog.require('org.patternfly.style.TypedModifier');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const Table = goog.require('org.patternfly.component.table.Table$impl');
exports = Table;
