goog.module('org.patternfly.component.table.Tbody');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.HTMLTableRowElement.$Overlay');
goog.require('elemental2.dom.HTMLTableSectionElement.$Overlay');
goog.require('java.lang.Iterable');
goog.require('java.lang.String');
goog.require('java.util.Comparator');
goog.require('java.util.Iterator');
goog.require('java.util.LinkedHashMap');
goog.require('java.util.List');
goog.require('java.util.Map');
goog.require('java.util.Spliterator');
goog.require('java.util.function.BiConsumer');
goog.require('java.util.function.Consumer');
goog.require('java.util.function.Function');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.ElementContainerMethods');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.Id');
goog.require('org.jboss.elemento.TypedBuilder');
goog.require('org.patternfly.component.AddItemHandler');
goog.require('org.patternfly.component.AurHandler');
goog.require('org.patternfly.component.HasItems');
goog.require('org.patternfly.component.Ordered');
goog.require('org.patternfly.component.RemoveItemHandler');
goog.require('org.patternfly.component.UpdateItemHandler');
goog.require('org.patternfly.component.emptystate.EmptyState');
goog.require('org.patternfly.component.table.TableSubComponent');
goog.require('org.patternfly.component.table.Td');
goog.require('org.patternfly.component.table.Tr');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.core.Roles');
goog.require('org.patternfly.layout.bullseye.Bullseye');
goog.require('org.patternfly.style.Classes');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const Tbody = goog.require('org.patternfly.component.table.Tbody$impl');
exports = Tbody;
