goog.module('org.patternfly.component.menu.MenuToggle');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.HTMLButtonElement.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('java.lang.Class');
goog.require('java.lang.String');
goog.require('java.util.function.Consumer');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.ButtonType');
goog.require('org.jboss.elemento.ElementTextMethods');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.logger.Logger');
goog.require('org.patternfly.component.BaseComponent');
goog.require('org.patternfly.component.ComponentIcon');
goog.require('org.patternfly.component.ComponentIconAndText');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.IconPosition');
goog.require('org.patternfly.component.ValidationStatus');
goog.require('org.patternfly.component.avatar.Avatar');
goog.require('org.patternfly.component.badge.Badge');
goog.require('org.patternfly.component.form.Checkbox');
goog.require('org.patternfly.component.menu.MenuToggleAction');
goog.require('org.patternfly.component.menu.MenuToggleType');
goog.require('org.patternfly.component.textinputgroup.BaseFilterInput');
goog.require('org.patternfly.component.textinputgroup.BaseSearchInput');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.icon.IconSets.rhUi');
goog.require('org.patternfly.icon.PredefinedIcon');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Modifiers');
goog.require('org.patternfly.style.Modifiers.Disabled');
goog.require('org.patternfly.style.Modifiers.FullHeight');
goog.require('org.patternfly.style.Modifiers.FullWidth');
goog.require('org.patternfly.style.Modifiers.Primary');
goog.require('org.patternfly.style.Modifiers.Secondary');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const MenuToggle = goog.require('org.patternfly.component.menu.MenuToggle$impl');
exports = MenuToggle;
