goog.module('org.patternfly.component.menu.MenuSearch');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.MutationRecord.$Overlay');
goog.require('elemental2.dom.Node.$Overlay');
goog.require('java.lang.Class');
goog.require('java.lang.String');
goog.require('java.util.function.Supplier');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Attachable');
goog.require('org.jboss.elemento.ElementContainerDelegate');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.logger.Logger');
goog.require('org.patternfly.component.menu.Menu');
goog.require('org.patternfly.component.menu.MenuSubComponent');
goog.require('org.patternfly.component.menu.NoResults');
goog.require('org.patternfly.component.menu.SearchFilter');
goog.require('org.patternfly.component.textinputgroup.SearchInput');
goog.require('org.patternfly.handler.ChangeHandler');
goog.require('org.patternfly.handler.ComponentHandler');
goog.require('org.patternfly.style.Classes');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const MenuSearch = goog.require('org.patternfly.component.menu.MenuSearch$impl');
exports = MenuSearch;
