goog.module('org.patternfly.component.menu.MenuItemAction');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('java.lang.String');
goog.require('java.util.ArrayList');
goog.require('java.util.List');
goog.require('java.util.function.Consumer');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.HTMLElementBuilder');
goog.require('org.jboss.elemento.Id');
goog.require('org.patternfly.component.ComponentIcon');
goog.require('org.patternfly.component.HasIdentifier');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.component.menu.Menu');
goog.require('org.patternfly.component.menu.MenuActionHandler');
goog.require('org.patternfly.component.menu.MenuItem');
goog.require('org.patternfly.component.menu.MenuSubComponent');
goog.require('org.patternfly.core.Dataset');
goog.require('org.patternfly.handler.ComponentHandler');
goog.require('org.patternfly.icon.PredefinedIcon');
goog.require('org.patternfly.style.Classes');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const MenuItemAction = goog.require('org.patternfly.component.menu.MenuItemAction$impl');
exports = MenuItemAction;
