goog.module('org.patternfly.component.menu.MultiTypeahead');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.promise.Promise.$Overlay');
goog.require('java.lang.String');
goog.require('java.util.List');
goog.require('java.util.function.Function');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.Elements');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.label.Label');
goog.require('org.patternfly.component.menu.Menu');
goog.require('org.patternfly.component.menu.MenuItem');
goog.require('org.patternfly.component.menu.MenuToggle');
goog.require('org.patternfly.component.menu.MultiMenuToggleMenu');
goog.require('org.patternfly.component.menu.NoResults');
goog.require('org.patternfly.component.menu.SearchFilter');
goog.require('org.patternfly.component.menu.StayOpenPredicate');
goog.require('org.patternfly.component.menu.Typeahead');
goog.require('org.patternfly.component.menu.TypeaheadSupport');
goog.require('org.patternfly.component.textinputgroup.BaseFilterInput');
goog.require('org.patternfly.component.textinputgroup.BaseTextInputGroup');
goog.require('org.patternfly.component.textinputgroup.FilterInput');
goog.require('org.patternfly.handler.ChangeHandler');
goog.require('org.patternfly.handler.CloseHandler');
goog.require('org.patternfly.handler.ComponentHandler');
goog.require('org.patternfly.style.Classes');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const MultiTypeahead = goog.require('org.patternfly.component.menu.MultiTypeahead$impl');
exports = MultiTypeahead;
