goog.module('org.patternfly.component.menu.TypeaheadSupport');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLInputElement.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('elemental2.promise.IThenable.$Overlay');
goog.require('elemental2.promise.Promise.$Overlay');
goog.require('java.lang.Object');
goog.require('java.lang.String');
goog.require('java.util.function.Function');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLInputElementBuilder');
goog.require('org.jboss.elemento.Key');
goog.require('org.jboss.elemento.TypedBuilder');
goog.require('org.patternfly.component.menu.MenuItem');
goog.require('org.patternfly.component.menu.MenuList');
goog.require('org.patternfly.component.menu.MenuToggleMenu');
goog.require('org.patternfly.component.menu.NoResults');
goog.require('org.patternfly.component.menu.PopperMenuToggleMenu');
goog.require('org.patternfly.component.menu.PopperTypeahead');
goog.require('org.patternfly.component.menu.Typeahead');
goog.require('org.patternfly.component.textinputgroup.BaseSearchInput');
goog.require('org.patternfly.component.textinputgroup.BaseTextInputGroup');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.core.Roles');
goog.require('org.patternfly.handler.ChangeHandler');
goog.require('org.patternfly.handler.ComponentHandler');
goog.require('org.patternfly.handler.ToggleHandler');
goog.require('org.patternfly.style.Classes');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const TypeaheadSupport = goog.require('org.patternfly.component.menu.TypeaheadSupport$impl');
exports = TypeaheadSupport;
