goog.module('org.patternfly.showcase.chart.DonutUtilizationChart$impl');

const $Util = goog.require('nativebootstrap.Util$impl');
const SnippetPage = goog.require('org.patternfly.showcase.SnippetPage$impl');

let DomGlobal_$Overlay = goog.forwardDeclare('elemental2.dom.DomGlobal.$Overlay$impl');
let HTMLDivElement_$Overlay = goog.forwardDeclare('elemental2.dom.HTMLDivElement.$Overlay$impl');
let Class = goog.forwardDeclare('java.lang.Class$impl');
let j_l_String = goog.forwardDeclare('java.lang.String$impl');
let j_u_function_Function = goog.forwardDeclare('java.util.function.Function$impl');
let Supplier = goog.forwardDeclare('java.util.function.Supplier$impl');
let $double = goog.forwardDeclare('javaemul.internal.primitives.$double$impl');
let $Overlay = goog.forwardDeclare('jsinterop.base.JsPropertyMap.$Overlay$impl');
let $Equality = goog.forwardDeclare('nativebootstrap.Equality$impl');
let Elements = goog.forwardDeclare('org.jboss.elemento.Elements$impl');
let HTMLContainerBuilder = goog.forwardDeclare('org.jboss.elemento.HTMLContainerBuilder$impl');
let ChartThemeColor = goog.forwardDeclare('org.patternfly.chart.ChartThemeColor$impl');
let Data_$Overlay = goog.forwardDeclare('org.patternfly.chart.Data.$Overlay$impl');
let LegendOrientation = goog.forwardDeclare('org.patternfly.chart.LegendOrientation$impl');
let LegendPosition = goog.forwardDeclare('org.patternfly.chart.LegendPosition$impl');
let Padding_$Overlay = goog.forwardDeclare('org.patternfly.chart.Padding.$Overlay$impl');
let SubTitlePosition = goog.forwardDeclare('org.patternfly.chart.SubTitlePosition$impl');
let DonutThreshold = goog.forwardDeclare('org.patternfly.chart.utilization.DonutThreshold$impl');
let DonutUtilization = goog.forwardDeclare('org.patternfly.chart.utilization.DonutUtilization$impl');
let Type = goog.forwardDeclare('org.patternfly.showcase.ApiDoc.Type$impl');
let Code = goog.forwardDeclare('org.patternfly.showcase.Code$impl');
let Data = goog.forwardDeclare('org.patternfly.showcase.Data$impl');
let Snippet = goog.forwardDeclare('org.patternfly.showcase.Snippet$impl');
let Chart_$Overlay = goog.forwardDeclare('org.patternfly.showcase.chart.Chart.$Overlay$impl');
let $Arrays = goog.forwardDeclare('vmbootstrap.Arrays$impl');
let $Casts = goog.forwardDeclare('vmbootstrap.Casts$impl');

class DonutUtilizationChart extends SnippetPage {
 /** @protected @nodts */
 constructor() {
  super();
 }
 /** @nodts @return {!DonutUtilizationChart} */
 static $create__() {
  DonutUtilizationChart.$clinit();
  let $instance = new DonutUtilizationChart();
  $instance.$ctor__org_patternfly_showcase_chart_DonutUtilizationChart__void();
  return $instance;
 }
 /** @nodts */
 $ctor__org_patternfly_showcase_chart_DonutUtilizationChart__void() {
  this.$ctor__org_patternfly_showcase_SnippetPage__org_patternfly_showcase_chart_Chart__void(/**@type {Object}*/ ($Casts.$to($Overlay.m_get__$devirt__jsinterop_base_JsPropertyMap__java_lang_String__java_lang_Object(Data.f_charts__org_patternfly_showcase_Data, 'donut-utilization'), Chart_$Overlay)));
  this.m_addHeader__java_lang_String__java_lang_String__void('donut-utilization', 'Donut utilization examples');
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-utilization', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('du-basic', 'Basic', Code.m_code__java_lang_String__java_lang_String('du-basic'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 230px; width: 230px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('75%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart example'), DonutUtilization))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 75)).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data) =>{
    let data_1 = /**@type {Object}*/ ($Casts.$to(data, Data_$Overlay));
    return !$Equality.$same(data_1.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_1.x) + ': ' + data_1.y + '%' : null;
   })))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-utilization', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('du-ral', 'Right aligned legend', Code.m_code__java_lang_String__java_lang_String('du-ral'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   let du = /**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('0%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart example'), DonutUtilization))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 0)).m_thresholds__arrayOf_double__org_patternfly_chart_utilization_DonutUtilization(/**@type {!Array<number>}*/ ($Arrays.$stampType([60, 90], $double))).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_2) =>{
    let data_3 = /**@type {Object}*/ ($Casts.$to(data_2, Data_$Overlay));
    return !$Equality.$same(data_3.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_3.x) + ': ' + data_3.y + '%' : null;
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: 0%', 'unused'], j_l_String))), DonutUtilization))).m_legendOrientation__org_patternfly_chart_LegendOrientation__org_jboss_elemento_TypedBuilder(LegendOrientation.f_vertical__org_patternfly_chart_LegendOrientation), DonutUtilization))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 225, 20, 20)), DonutUtilization))).m_width__int__org_jboss_elemento_TypedBuilder(435), DonutUtilization));
   DomGlobal_$Overlay.m_setInterval__elemental2_dom_DomGlobal_SetIntervalCallbackFn__double__arrayOf_java_lang_Object__double((.../** ...* */ __) =>{
    let previous = du.m_data__org_patternfly_chart_Data().y;
    let current = (previous + 10) % 100;
    du.m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', current));
    du.m_title__java_lang_String__org_jboss_elemento_TypedBuilder(current + '%');
    du.m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: ' + current + '%', 'unused'], j_l_String)));
   }, 1000, []);
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 230px; width: 435px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(du), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-utilization', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('du-inv-ral', 'Inverted with right aligned legend', Code.m_code__java_lang_String__java_lang_String('du-inv-ral'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   let du_1 = /**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('0%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart example'), DonutUtilization))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 0)).m_thresholds__arrayOf_double__org_patternfly_chart_utilization_DonutUtilization(/**@type {!Array<number>}*/ ($Arrays.$stampType([60, 20], $double))).m_invert__org_patternfly_chart_utilization_DonutUtilization().m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_4) =>{
    let data_5 = /**@type {Object}*/ ($Casts.$to(data_4, Data_$Overlay));
    return !$Equality.$same(data_5.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_5.x) + ': ' + data_5.y + '%' : null;
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: 0%', 'unused'], j_l_String))), DonutUtilization))).m_legendOrientation__org_patternfly_chart_LegendOrientation__org_jboss_elemento_TypedBuilder(LegendOrientation.f_vertical__org_patternfly_chart_LegendOrientation), DonutUtilization))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 225, 20, 20)), DonutUtilization))).m_width__int__org_jboss_elemento_TypedBuilder(435), DonutUtilization));
   DomGlobal_$Overlay.m_setInterval__elemental2_dom_DomGlobal_SetIntervalCallbackFn__double__arrayOf_java_lang_Object__double((.../** ...* */ ___1) =>{
    let previous_1 = du_1.m_data__org_patternfly_chart_Data().y;
    let current_1 = ((previous_1 - 10) % 100 + 100) % 100;
    du_1.m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', current_1));
    du_1.m_title__java_lang_String__org_jboss_elemento_TypedBuilder(current_1 + '%');
    du_1.m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: ' + current_1 + '%', 'unused'], j_l_String)));
   }, 1000, []);
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 230px; width: 435px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(du_1), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-utilization', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('du-bavl', 'Bottom aligned vertical legend', Code.m_code__java_lang_String__java_lang_String('du-bavl'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   let du_2 = /**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('0%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart example'), DonutUtilization))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 0)).m_thresholds__arrayOf_double__org_patternfly_chart_utilization_DonutUtilization(/**@type {!Array<number>}*/ ($Arrays.$stampType([60, 90], $double))).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_6) =>{
    let data_7 = /**@type {Object}*/ ($Casts.$to(data_6, Data_$Overlay));
    return !$Equality.$same(data_7.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_7.x) + ': ' + data_7.y + '%' : null;
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: 0%', 'unused'], j_l_String))), DonutUtilization))).m_legendOrientation__org_patternfly_chart_LegendOrientation__org_jboss_elemento_TypedBuilder(LegendOrientation.f_vertical__org_patternfly_chart_LegendOrientation), DonutUtilization))).m_legendPosition__org_patternfly_chart_LegendPosition__org_jboss_elemento_TypedBuilder(LegendPosition.f_bottom__org_patternfly_chart_LegendPosition), DonutUtilization))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 20, 75, 20)), DonutUtilization))).m_themeColor__org_patternfly_chart_ChartThemeColor__org_jboss_elemento_TypedBuilder(ChartThemeColor.f_green__org_patternfly_chart_ChartThemeColor), DonutUtilization))).m_height__int__org_jboss_elemento_TypedBuilder(300), DonutUtilization))).m_width__int__org_jboss_elemento_TypedBuilder(230), DonutUtilization));
   DomGlobal_$Overlay.m_setInterval__elemental2_dom_DomGlobal_SetIntervalCallbackFn__double__arrayOf_java_lang_Object__double((.../** ...* */ ___2) =>{
    let previous_2 = du_2.m_data__org_patternfly_chart_Data().y;
    let current_2 = (previous_2 + 10) % 100;
    du_2.m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', current_2));
    du_2.m_title__java_lang_String__org_jboss_elemento_TypedBuilder(current_2 + '%');
    du_2.m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: ' + current_2 + '%', 'unused'], j_l_String)));
   }, 1000, []);
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 300px; width: 230px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(du_2), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-utilization', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('du-bal', 'Bottom aligned legend', Code.m_code__java_lang_String__java_lang_String('du-bal'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 275px; width: 300px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('45%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart example'), DonutUtilization))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 45)).m_thresholds__arrayOf_double__org_patternfly_chart_utilization_DonutUtilization(/**@type {!Array<number>}*/ ($Arrays.$stampType([60, 90], $double))).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_8) =>{
    let data_9 = /**@type {Object}*/ ($Casts.$to(data_8, Data_$Overlay));
    return !$Equality.$same(data_9.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_9.x) + ': ' + data_9.y + '%' : null;
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: 45%', 'unused'], j_l_String))), DonutUtilization))).m_legendPosition__org_patternfly_chart_LegendPosition__org_jboss_elemento_TypedBuilder(LegendPosition.f_bottom__org_patternfly_chart_LegendPosition), DonutUtilization))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 20, 65, 20)), DonutUtilization))).m_height__int__org_jboss_elemento_TypedBuilder(275), DonutUtilization))).m_width__int__org_jboss_elemento_TypedBuilder(300), DonutUtilization))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-utilization', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('du-small', 'Small', Code.m_code__java_lang_String__java_lang_String('du-small'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 175px; width: 175px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('75%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart example'), DonutUtilization))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 75)).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_10) =>{
    let data_11 = /**@type {Object}*/ ($Casts.$to(data_10, Data_$Overlay));
    return !$Equality.$same(data_11.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_11.x) + ': ' + data_11.y + '%' : null;
   }))).m_height__int__org_jboss_elemento_TypedBuilder(175), DonutUtilization))).m_width__int__org_jboss_elemento_TypedBuilder(175), DonutUtilization))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-utilization', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('du-small-ral', 'Small with right aligned legend', Code.m_code__java_lang_String__java_lang_String('du-small-ral'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   let du_3 = /**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('0%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart example'), DonutUtilization))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 0)).m_thresholds__arrayOf_double__org_patternfly_chart_utilization_DonutUtilization(/**@type {!Array<number>}*/ ($Arrays.$stampType([60, 90], $double))).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_12) =>{
    let data_13 = /**@type {Object}*/ ($Casts.$to(data_12, Data_$Overlay));
    return !$Equality.$same(data_13.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_13.x) + ': ' + data_13.y + '%' : null;
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: 0%', 'unused'], j_l_String))), DonutUtilization))).m_legendOrientation__org_patternfly_chart_LegendOrientation__org_jboss_elemento_TypedBuilder(LegendOrientation.f_vertical__org_patternfly_chart_LegendOrientation), DonutUtilization))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 195, 20, 20)), DonutUtilization))).m_width__int__org_jboss_elemento_TypedBuilder(350), DonutUtilization))).m_height__int__org_jboss_elemento_TypedBuilder(175), DonutUtilization));
   DomGlobal_$Overlay.m_setInterval__elemental2_dom_DomGlobal_SetIntervalCallbackFn__double__arrayOf_java_lang_Object__double((.../** ...* */ ___3) =>{
    let previous_3 = du_3.m_data__org_patternfly_chart_Data().y;
    let current_3 = (previous_3 + 10) % 100;
    du_3.m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', current_3));
    du_3.m_title__java_lang_String__org_jboss_elemento_TypedBuilder(current_3 + '%');
    du_3.m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: ' + current_3 + '%', 'unused'], j_l_String)));
   }, 1000, []);
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 175px; width: 350px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(du_3), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-utilization', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('du-small-bas', 'Small with bottom aligned subtitle', Code.m_code__java_lang_String__java_lang_String('du-small-bas'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 185px; width: 350px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('45%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_subTitlePosition__org_patternfly_chart_SubTitlePosition__org_jboss_elemento_TypedBuilder(SubTitlePosition.f_bottom__org_patternfly_chart_SubTitlePosition), DonutUtilization))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart example'), DonutUtilization))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 45)).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_14) =>{
    let data_15 = /**@type {Object}*/ ($Casts.$to(data_14, Data_$Overlay));
    return !$Equality.$same(data_15.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_15.x) + ': ' + data_15.y + '%' : null;
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: 45%', 'unused'], j_l_String))), DonutUtilization))).m_legendOrientation__org_patternfly_chart_LegendOrientation__org_jboss_elemento_TypedBuilder(LegendOrientation.f_vertical__org_patternfly_chart_LegendOrientation), DonutUtilization))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 195, 20, 20)), DonutUtilization))).m_height__int__org_jboss_elemento_TypedBuilder(185), DonutUtilization))).m_width__int__org_jboss_elemento_TypedBuilder(350), DonutUtilization))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-utilization', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('du-small-ras', 'Small with right aligned subtitle', Code.m_code__java_lang_String__java_lang_String('du-small-ras'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 200px; width: 350px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('45%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_subTitlePosition__org_patternfly_chart_SubTitlePosition__org_jboss_elemento_TypedBuilder(SubTitlePosition.f_right__org_patternfly_chart_SubTitlePosition), DonutUtilization))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart example'), DonutUtilization))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 45)).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_16) =>{
    let data_17 = /**@type {Object}*/ ($Casts.$to(data_16, Data_$Overlay));
    return !$Equality.$same(data_17.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_17.x) + ': ' + data_17.y + '%' : null;
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: 45%', 'unused'], j_l_String))), DonutUtilization))).m_legendPosition__org_patternfly_chart_LegendPosition__org_jboss_elemento_TypedBuilder(LegendPosition.f_bottom__org_patternfly_chart_LegendPosition), DonutUtilization))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 20, 45, 20)), DonutUtilization))).m_height__int__org_jboss_elemento_TypedBuilder(200), DonutUtilization))).m_width__int__org_jboss_elemento_TypedBuilder(350), DonutUtilization))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addHeader__java_lang_String__java_lang_String__void('donut-threshold', 'Donut threshold examples');
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-threshold', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('dt-static', 'Static thresholds', Code.m_code__java_lang_String__java_lang_String('dt-static'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 230px; width: 230px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to(DonutThreshold.m_donutThreshold__org_patternfly_chart_utilization_DonutThreshold().m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart with static threshold example'), DonutThreshold))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutThreshold))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutThreshold([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Warning at 60%', 60), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Danger at 90%', 90)]).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutThreshold(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_18) =>{
    let data_19 = /**@type {Object}*/ ($Casts.$to(data_18, Data_$Overlay));
    return !$Equality.$same(data_19.x, null) ? data_19.x : null;
   }))).m_addUtilization__org_patternfly_chart_utilization_DonutUtilization__org_patternfly_chart_utilization_DonutThreshold((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('45%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 45)).m_thresholds__arrayOf_double__org_patternfly_chart_utilization_DonutUtilization(/**@type {!Array<number>}*/ ($Arrays.$stampType([60, 90], $double))).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_20) =>{
    let data_21 = /**@type {Object}*/ ($Casts.$to(data_20, Data_$Overlay));
    return !$Equality.$same(data_21.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_21.x) + ': ' + data_21.y + '%' : null;
   }))))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-threshold', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('dt-ral', 'Static thresholds with right aligned legend', Code.m_code__java_lang_String__java_lang_String('dt-ral'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   let du_4 = DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization();
   let dt = (/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to(DonutThreshold.m_donutThreshold__org_patternfly_chart_utilization_DonutThreshold().m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart with static threshold example'), DonutThreshold))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutThreshold))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutThreshold([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Warning at 60%', 60), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Danger at 90%', 90)]).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutThreshold(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_22) =>{
    let data_23 = /**@type {Object}*/ ($Casts.$to(data_22, Data_$Overlay));
    return !$Equality.$same(data_23.x, null) ? data_23.x : null;
   }))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 290, 20, 20)), DonutThreshold))).m_width__int__org_jboss_elemento_TypedBuilder(500), DonutThreshold))).m_addUtilization__org_patternfly_chart_utilization_DonutUtilization__org_patternfly_chart_utilization_DonutThreshold(/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(du_4.m_title__java_lang_String__org_jboss_elemento_TypedBuilder('0%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 0)).m_thresholds__arrayOf_double__org_patternfly_chart_utilization_DonutUtilization(/**@type {!Array<number>}*/ ($Arrays.$stampType([60, 90], $double))).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_24) =>{
    let data_25 = /**@type {Object}*/ ($Casts.$to(data_24, Data_$Overlay));
    return !$Equality.$same(data_25.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_25.x) + ': ' + data_25.y + '%' : null;
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: 0%', 'Warning threshold at 60%', 'Danger threshold at 90%'], j_l_String))), DonutUtilization))).m_legendOrientation__org_patternfly_chart_LegendOrientation__org_jboss_elemento_TypedBuilder(LegendOrientation.f_vertical__org_patternfly_chart_LegendOrientation), DonutUtilization)));
   DomGlobal_$Overlay.m_setInterval__elemental2_dom_DomGlobal_SetIntervalCallbackFn__double__arrayOf_java_lang_Object__double((.../** ...* */ ___4) =>{
    let previous_4 = du_4.m_data__org_patternfly_chart_Data().y;
    let current_4 = (previous_4 + 10) % 100;
    du_4.m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', current_4));
    du_4.m_title__java_lang_String__org_jboss_elemento_TypedBuilder(current_4 + '%');
    du_4.m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: ' + current_4 + '%', 'Warning threshold at 60%', 'Danger threshold at 90%'], j_l_String)));
   }, 1000, []);
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 230px; width: 500px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(dt), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-threshold', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('dt-inv-ral', 'Inverted static thresholds with right aligned legend', Code.m_code__java_lang_String__java_lang_String('dt-inv-ral'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   let du_5 = DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization();
   let dt_1 = (/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to(DonutThreshold.m_donutThreshold__org_patternfly_chart_utilization_DonutThreshold().m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart with static threshold example'), DonutThreshold))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutThreshold))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutThreshold([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Warning at 60%', 60), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Danger at 20%', 20)]).m_invert__org_patternfly_chart_utilization_DonutThreshold().m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutThreshold(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_26) =>{
    let data_27 = /**@type {Object}*/ ($Casts.$to(data_26, Data_$Overlay));
    return !$Equality.$same(data_27.x, null) ? data_27.x : null;
   }))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 290, 20, 20)), DonutThreshold))).m_width__int__org_jboss_elemento_TypedBuilder(500), DonutThreshold))).m_addUtilization__org_patternfly_chart_utilization_DonutUtilization__org_patternfly_chart_utilization_DonutThreshold(/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(du_5.m_title__java_lang_String__org_jboss_elemento_TypedBuilder('0%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 0)).m_thresholds__arrayOf_double__org_patternfly_chart_utilization_DonutUtilization(/**@type {!Array<number>}*/ ($Arrays.$stampType([60, 20], $double))).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_28) =>{
    let data_29 = /**@type {Object}*/ ($Casts.$to(data_28, Data_$Overlay));
    return !$Equality.$same(data_29.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_29.x) + ': ' + data_29.y + '%' : null;
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: 0%', 'Warning threshold at 60%', 'Danger threshold at 20%'], j_l_String))), DonutUtilization))).m_legendOrientation__org_patternfly_chart_LegendOrientation__org_jboss_elemento_TypedBuilder(LegendOrientation.f_vertical__org_patternfly_chart_LegendOrientation), DonutUtilization)));
   DomGlobal_$Overlay.m_setInterval__elemental2_dom_DomGlobal_SetIntervalCallbackFn__double__arrayOf_java_lang_Object__double((.../** ...* */ ___5) =>{
    let previous_5 = du_5.m_data__org_patternfly_chart_Data().y;
    let current_5 = ((previous_5 - 10) % 100 + 100) % 100;
    du_5.m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', current_5));
    du_5.m_title__java_lang_String__org_jboss_elemento_TypedBuilder(current_5 + '%');
    du_5.m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: ' + current_5 + '%', 'Warning threshold at 60%', 'Danger threshold at 20%'], j_l_String)));
   }, 1000, []);
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 230px; width: 500px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(dt_1), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-threshold', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('dt-ral', 'Static thresholds with custom legend', Code.m_code__java_lang_String__java_lang_String('dt-ral'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   let du_6 = DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization();
   let dt_2 = (/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to(DonutThreshold.m_donutThreshold__org_patternfly_chart_utilization_DonutThreshold().m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart with static threshold example'), DonutThreshold))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutThreshold))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutThreshold([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Warning at 60%', 60), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Danger at 90%', 90)]).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutThreshold(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_30) =>{
    let data_31 = /**@type {Object}*/ ($Casts.$to(data_30, Data_$Overlay));
    return !$Equality.$same(data_31.x, null) ? data_31.x : null;
   }))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 20, 125, 20)), DonutThreshold))).m_height__int__org_jboss_elemento_TypedBuilder(350), DonutThreshold))).m_width__int__org_jboss_elemento_TypedBuilder(230), DonutThreshold))).m_addUtilization__org_patternfly_chart_utilization_DonutUtilization__org_patternfly_chart_utilization_DonutThreshold(/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(du_6.m_title__java_lang_String__org_jboss_elemento_TypedBuilder('0%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 0)).m_thresholds__arrayOf_double__org_patternfly_chart_utilization_DonutUtilization(/**@type {!Array<number>}*/ ($Arrays.$stampType([60, 90], $double))).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_32) =>{
    let data_33 = /**@type {Object}*/ ($Casts.$to(data_32, Data_$Overlay));
    return !$Equality.$same(data_33.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_33.x) + ': ' + data_33.y + '%' : null;
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: 0%', 'Warning threshold at 60%', 'Danger threshold at 90%'], j_l_String))), DonutUtilization))).m_legendOrientation__org_patternfly_chart_LegendOrientation__org_jboss_elemento_TypedBuilder(LegendOrientation.f_vertical__org_patternfly_chart_LegendOrientation), DonutUtilization))).m_legendPosition__org_patternfly_chart_LegendPosition__org_jboss_elemento_TypedBuilder(LegendPosition.f_bottom__org_patternfly_chart_LegendPosition), DonutUtilization))).m_themeColor__org_patternfly_chart_ChartThemeColor__org_jboss_elemento_TypedBuilder(ChartThemeColor.f_green__org_patternfly_chart_ChartThemeColor), DonutUtilization)));
   DomGlobal_$Overlay.m_setInterval__elemental2_dom_DomGlobal_SetIntervalCallbackFn__double__arrayOf_java_lang_Object__double((.../** ...* */ ___6) =>{
    let previous_6 = du_6.m_data__org_patternfly_chart_Data().y;
    let current_6 = (previous_6 + 10) % 100;
    du_6.m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', current_6));
    du_6.m_title__java_lang_String__org_jboss_elemento_TypedBuilder(current_6 + '%');
    du_6.m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: ' + current_6 + '%', 'Warning threshold at 60%', 'Danger threshold at 90%'], j_l_String)));
   }, 1000, []);
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 350px; width: 230px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(dt_2), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-threshold', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('dt-bal', 'Static thresholds with bottom aligned legend', Code.m_code__java_lang_String__java_lang_String('dt-bal'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 275px; width: 675px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to(DonutThreshold.m_donutThreshold__org_patternfly_chart_utilization_DonutThreshold().m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart with static threshold example'), DonutThreshold))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutThreshold))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutThreshold([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Warning at 60%', 60), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Danger at 90%', 90)]).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutThreshold(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_34) =>{
    let data_35 = /**@type {Object}*/ ($Casts.$to(data_34, Data_$Overlay));
    return !$Equality.$same(data_35.x, null) ? data_35.x : null;
   }))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 20, 65, 20)), DonutThreshold))).m_height__int__org_jboss_elemento_TypedBuilder(275), DonutThreshold))).m_width__int__org_jboss_elemento_TypedBuilder(675), DonutThreshold))).m_addUtilization__org_patternfly_chart_utilization_DonutUtilization__org_patternfly_chart_utilization_DonutThreshold(/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('45%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 45)).m_thresholds__arrayOf_double__org_patternfly_chart_utilization_DonutUtilization(/**@type {!Array<number>}*/ ($Arrays.$stampType([60, 90], $double))).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_36) =>{
    let data_37 = /**@type {Object}*/ ($Casts.$to(data_36, Data_$Overlay));
    return !$Equality.$same(data_37.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_37.x) + ': ' + data_37.y + '%' : null;
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: 0%', 'Warning threshold at 60%', 'Danger threshold at 90%'], j_l_String))), DonutUtilization))).m_legendPosition__org_patternfly_chart_LegendPosition__org_jboss_elemento_TypedBuilder(LegendPosition.f_bottom__org_patternfly_chart_LegendPosition), DonutUtilization)))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-threshold', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('dt-small-static', 'Small with static thresholds', Code.m_code__java_lang_String__java_lang_String('dt-small-static'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 185px; width: 185px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to(DonutThreshold.m_donutThreshold__org_patternfly_chart_utilization_DonutThreshold().m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart with static threshold example'), DonutThreshold))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutThreshold))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutThreshold([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Warning at 60%', 60), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Danger at 90%', 90)]).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutThreshold(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_38) =>{
    let data_39 = /**@type {Object}*/ ($Casts.$to(data_38, Data_$Overlay));
    return !$Equality.$same(data_39.x, null) ? data_39.x : null;
   }))).m_height__int__org_jboss_elemento_TypedBuilder(185), DonutThreshold))).m_width__int__org_jboss_elemento_TypedBuilder(185), DonutThreshold))).m_addUtilization__org_patternfly_chart_utilization_DonutUtilization__org_patternfly_chart_utilization_DonutThreshold((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('45%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 45)).m_thresholds__arrayOf_double__org_patternfly_chart_utilization_DonutUtilization(/**@type {!Array<number>}*/ ($Arrays.$stampType([60, 90], $double))).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_40) =>{
    let data_41 = /**@type {Object}*/ ($Casts.$to(data_40, Data_$Overlay));
    return !$Equality.$same(data_41.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_41.x) + ': ' + data_41.y + '%' : null;
   }))))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-threshold', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('dt-small-ral', 'Small with static thresholds and right aligned legend', Code.m_code__java_lang_String__java_lang_String('dt-small-ral'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   let du_7 = DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization();
   let dt_3 = (/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to(DonutThreshold.m_donutThreshold__org_patternfly_chart_utilization_DonutThreshold().m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart with static threshold example'), DonutThreshold))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutThreshold))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutThreshold([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Warning at 60%', 60), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Danger at 90%', 90)]).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutThreshold(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_42) =>{
    let data_43 = /**@type {Object}*/ ($Casts.$to(data_42, Data_$Overlay));
    return !$Equality.$same(data_43.x, null) ? data_43.x : null;
   }))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 260, 20, 20)), DonutThreshold))).m_height__int__org_jboss_elemento_TypedBuilder(185), DonutThreshold))).m_width__int__org_jboss_elemento_TypedBuilder(425), DonutThreshold))).m_addUtilization__org_patternfly_chart_utilization_DonutUtilization__org_patternfly_chart_utilization_DonutThreshold(/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(du_7.m_title__java_lang_String__org_jboss_elemento_TypedBuilder('0%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 0)).m_thresholds__arrayOf_double__org_patternfly_chart_utilization_DonutUtilization(/**@type {!Array<number>}*/ ($Arrays.$stampType([60, 90], $double))).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_44) =>{
    let data_45 = /**@type {Object}*/ ($Casts.$to(data_44, Data_$Overlay));
    return !$Equality.$same(data_45.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_45.x) + ': ' + data_45.y + '%' : null;
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: 0%', 'Warning threshold at 60%', 'Danger threshold at 90%'], j_l_String))), DonutUtilization))).m_legendOrientation__org_patternfly_chart_LegendOrientation__org_jboss_elemento_TypedBuilder(LegendOrientation.f_vertical__org_patternfly_chart_LegendOrientation), DonutUtilization)));
   DomGlobal_$Overlay.m_setInterval__elemental2_dom_DomGlobal_SetIntervalCallbackFn__double__arrayOf_java_lang_Object__double((.../** ...* */ ___7) =>{
    let previous_7 = du_7.m_data__org_patternfly_chart_Data().y;
    let current_7 = (previous_7 + 10) % 100;
    du_7.m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', current_7));
    du_7.m_title__java_lang_String__org_jboss_elemento_TypedBuilder(current_7 + '%');
    du_7.m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: ' + current_7 + '%', 'Warning threshold at 60%', 'Danger threshold at 90%'], j_l_String)));
   }, 1000, []);
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 185px; width: 425px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(dt_3), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-threshold', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('dt-small-subtitle', 'Small with subtitle', Code.m_code__java_lang_String__java_lang_String('dt-small-subtitle'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 200px; width: 425px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to(DonutThreshold.m_donutThreshold__org_patternfly_chart_utilization_DonutThreshold().m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart with static threshold example'), DonutThreshold))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutThreshold))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutThreshold([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Warning at 60%', 60), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Danger at 90%', 90)]).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutThreshold(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_46) =>{
    let data_47 = /**@type {Object}*/ ($Casts.$to(data_46, Data_$Overlay));
    return !$Equality.$same(data_47.x, null) ? data_47.x : null;
   }))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 260, 20, 20)), DonutThreshold))).m_height__int__org_jboss_elemento_TypedBuilder(200), DonutThreshold))).m_width__int__org_jboss_elemento_TypedBuilder(425), DonutThreshold))).m_addUtilization__org_patternfly_chart_utilization_DonutUtilization__org_patternfly_chart_utilization_DonutThreshold(/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('45%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_subTitlePosition__org_patternfly_chart_SubTitlePosition__org_jboss_elemento_TypedBuilder(SubTitlePosition.f_bottom__org_patternfly_chart_SubTitlePosition), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 45)).m_thresholds__arrayOf_double__org_patternfly_chart_utilization_DonutUtilization(/**@type {!Array<number>}*/ ($Arrays.$stampType([60, 90], $double))).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_48) =>{
    let data_49 = /**@type {Object}*/ ($Casts.$to(data_48, Data_$Overlay));
    return !$Equality.$same(data_49.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_49.x) + ': ' + data_49.y + '%' : null;
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: 45%', 'Warning threshold at 60%', 'Danger threshold at 90%'], j_l_String))), DonutUtilization))).m_legendOrientation__org_patternfly_chart_LegendOrientation__org_jboss_elemento_TypedBuilder(LegendOrientation.f_vertical__org_patternfly_chart_LegendOrientation), DonutUtilization)))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__java_lang_String__org_patternfly_showcase_Snippet__void('donut-threshold', Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('dt-small-subtitle-right', 'Small with thresholds and right aligned subtitle', Code.m_code__java_lang_String__java_lang_String('dt-small-subtitle-right'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 225px; width: 675px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to((/**@type {DonutThreshold}*/ ($Casts.$to(DonutThreshold.m_donutThreshold__org_patternfly_chart_utilization_DonutThreshold().m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut utilization chart with static threshold example'), DonutThreshold))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Storage capacity'), DonutThreshold))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutThreshold([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Warning at 60%', 60), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Danger at 90%', 90)]).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutThreshold(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_50) =>{
    let data_51 = /**@type {Object}*/ ($Casts.$to(data_50, Data_$Overlay));
    return !$Equality.$same(data_51.x, null) ? data_51.x : null;
   }))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 20, 60, 20)), DonutThreshold))).m_height__int__org_jboss_elemento_TypedBuilder(225), DonutThreshold))).m_width__int__org_jboss_elemento_TypedBuilder(675), DonutThreshold))).m_addUtilization__org_patternfly_chart_utilization_DonutUtilization__org_patternfly_chart_utilization_DonutThreshold(/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to((/**@type {DonutUtilization}*/ ($Casts.$to(DonutUtilization.m_donutUtilization__org_patternfly_chart_utilization_DonutUtilization().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('45%'), DonutUtilization))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('of 100 GBps'), DonutUtilization))).m_subTitlePosition__org_patternfly_chart_SubTitlePosition__org_jboss_elemento_TypedBuilder(SubTitlePosition.f_right__org_patternfly_chart_SubTitlePosition), DonutUtilization))).m_data__org_patternfly_chart_Data__org_patternfly_chart_utilization_DonutUtilization(Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Storage capacity', 45)).m_thresholds__arrayOf_double__org_patternfly_chart_utilization_DonutUtilization(/**@type {!Array<number>}*/ ($Arrays.$stampType([60, 90], $double))).m_labels__java_util_function_Function__org_patternfly_chart_utilization_DonutUtilization(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_52) =>{
    let data_53 = /**@type {Object}*/ ($Casts.$to(data_52, Data_$Overlay));
    return !$Equality.$same(data_53.x, null) ? j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_53.x) + ': ' + data_53.y + '%' : null;
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Storage capacity: 45%', 'Warning threshold at 60%', 'Danger threshold at 90%'], j_l_String))), DonutUtilization))).m_legendPosition__org_patternfly_chart_LegendPosition__org_jboss_elemento_TypedBuilder(LegendPosition.f_bottom__org_patternfly_chart_LegendPosition), DonutUtilization)))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_startApiDocs__java_lang_Class__void(Class.$get(DonutUtilization));
  this.m_addApiDoc__java_lang_Class__org_patternfly_showcase_ApiDoc_Type__void(Class.$get(DonutUtilization), Type.f_chart__org_patternfly_showcase_ApiDoc_Type);
  this.m_addApiDoc__java_lang_Class__org_patternfly_showcase_ApiDoc_Type__void(Class.$get(DonutThreshold), Type.f_chart__org_patternfly_showcase_ApiDoc_Type);
 }
 /** @nodts */
 static $clinit() {
  DonutUtilizationChart.$clinit = () =>{};
  DonutUtilizationChart.$loadModules();
  SnippetPage.$clinit();
 }
 /** @nodts @return {boolean} */
 static $isInstance(/** ? */ instance) {
  return instance instanceof DonutUtilizationChart;
 }
 
 /** @nodts */
 static $loadModules() {
  DomGlobal_$Overlay = goog.module.get('elemental2.dom.DomGlobal.$Overlay$impl');
  HTMLDivElement_$Overlay = goog.module.get('elemental2.dom.HTMLDivElement.$Overlay$impl');
  Class = goog.module.get('java.lang.Class$impl');
  j_l_String = goog.module.get('java.lang.String$impl');
  j_u_function_Function = goog.module.get('java.util.function.Function$impl');
  Supplier = goog.module.get('java.util.function.Supplier$impl');
  $double = goog.module.get('javaemul.internal.primitives.$double$impl');
  $Overlay = goog.module.get('jsinterop.base.JsPropertyMap.$Overlay$impl');
  $Equality = goog.module.get('nativebootstrap.Equality$impl');
  Elements = goog.module.get('org.jboss.elemento.Elements$impl');
  HTMLContainerBuilder = goog.module.get('org.jboss.elemento.HTMLContainerBuilder$impl');
  ChartThemeColor = goog.module.get('org.patternfly.chart.ChartThemeColor$impl');
  Data_$Overlay = goog.module.get('org.patternfly.chart.Data.$Overlay$impl');
  LegendOrientation = goog.module.get('org.patternfly.chart.LegendOrientation$impl');
  LegendPosition = goog.module.get('org.patternfly.chart.LegendPosition$impl');
  Padding_$Overlay = goog.module.get('org.patternfly.chart.Padding.$Overlay$impl');
  SubTitlePosition = goog.module.get('org.patternfly.chart.SubTitlePosition$impl');
  DonutThreshold = goog.module.get('org.patternfly.chart.utilization.DonutThreshold$impl');
  DonutUtilization = goog.module.get('org.patternfly.chart.utilization.DonutUtilization$impl');
  Type = goog.module.get('org.patternfly.showcase.ApiDoc.Type$impl');
  Code = goog.module.get('org.patternfly.showcase.Code$impl');
  Data = goog.module.get('org.patternfly.showcase.Data$impl');
  Snippet = goog.module.get('org.patternfly.showcase.Snippet$impl');
  Chart_$Overlay = goog.module.get('org.patternfly.showcase.chart.Chart.$Overlay$impl');
  $Arrays = goog.module.get('vmbootstrap.Arrays$impl');
  $Casts = goog.module.get('vmbootstrap.Casts$impl');
 }
}
$Util.$setClassMetadata(DonutUtilizationChart, 'org.patternfly.showcase.chart.DonutUtilizationChart');

exports = DonutUtilizationChart;

//# sourceMappingURL=DonutUtilizationChart.js.map
