goog.module('org.patternfly.showcase.chart.DonutChart');

goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('java.lang.Class');
goog.require('java.lang.String');
goog.require('java.util.function.Function');
goog.require('java.util.function.Supplier');
goog.require('jsinterop.base.JsPropertyMap.$Overlay');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.chart.ChartThemeColor');
goog.require('org.patternfly.chart.Data.$Overlay');
goog.require('org.patternfly.chart.LegendOrientation');
goog.require('org.patternfly.chart.LegendPosition');
goog.require('org.patternfly.chart.Padding.$Overlay');
goog.require('org.patternfly.chart.SubTitlePosition');
goog.require('org.patternfly.chart.donut.Donut');
goog.require('org.patternfly.showcase.ApiDoc.Type');
goog.require('org.patternfly.showcase.Code');
goog.require('org.patternfly.showcase.Data');
goog.require('org.patternfly.showcase.Snippet');
goog.require('org.patternfly.showcase.SnippetPage');
goog.require('org.patternfly.showcase.chart.Chart.$Overlay');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const DonutChart = goog.require('org.patternfly.showcase.chart.DonutChart$impl');
exports = DonutChart;
