goog.module('org.patternfly.showcase.chart.DonutChart$impl');

const $Util = goog.require('nativebootstrap.Util$impl');
const SnippetPage = goog.require('org.patternfly.showcase.SnippetPage$impl');

let HTMLDivElement_$Overlay = goog.forwardDeclare('elemental2.dom.HTMLDivElement.$Overlay$impl');
let Class = goog.forwardDeclare('java.lang.Class$impl');
let j_l_String = goog.forwardDeclare('java.lang.String$impl');
let j_u_function_Function = goog.forwardDeclare('java.util.function.Function$impl');
let Supplier = goog.forwardDeclare('java.util.function.Supplier$impl');
let $Overlay = goog.forwardDeclare('jsinterop.base.JsPropertyMap.$Overlay$impl');
let Elements = goog.forwardDeclare('org.jboss.elemento.Elements$impl');
let HTMLContainerBuilder = goog.forwardDeclare('org.jboss.elemento.HTMLContainerBuilder$impl');
let ChartThemeColor = goog.forwardDeclare('org.patternfly.chart.ChartThemeColor$impl');
let Data_$Overlay = goog.forwardDeclare('org.patternfly.chart.Data.$Overlay$impl');
let LegendOrientation = goog.forwardDeclare('org.patternfly.chart.LegendOrientation$impl');
let LegendPosition = goog.forwardDeclare('org.patternfly.chart.LegendPosition$impl');
let Padding_$Overlay = goog.forwardDeclare('org.patternfly.chart.Padding.$Overlay$impl');
let SubTitlePosition = goog.forwardDeclare('org.patternfly.chart.SubTitlePosition$impl');
let Donut = goog.forwardDeclare('org.patternfly.chart.donut.Donut$impl');
let Type = goog.forwardDeclare('org.patternfly.showcase.ApiDoc.Type$impl');
let Code = goog.forwardDeclare('org.patternfly.showcase.Code$impl');
let Data = goog.forwardDeclare('org.patternfly.showcase.Data$impl');
let Snippet = goog.forwardDeclare('org.patternfly.showcase.Snippet$impl');
let Chart_$Overlay = goog.forwardDeclare('org.patternfly.showcase.chart.Chart.$Overlay$impl');
let $Arrays = goog.forwardDeclare('vmbootstrap.Arrays$impl');
let $Casts = goog.forwardDeclare('vmbootstrap.Casts$impl');

class DonutChart extends SnippetPage {
 /** @protected @nodts */
 constructor() {
  super();
 }
 /** @nodts @return {!DonutChart} */
 static $create__() {
  DonutChart.$clinit();
  let $instance = new DonutChart();
  $instance.$ctor__org_patternfly_showcase_chart_DonutChart__void();
  return $instance;
 }
 /** @nodts */
 $ctor__org_patternfly_showcase_chart_DonutChart__void() {
  this.$ctor__org_patternfly_showcase_SnippetPage__org_patternfly_showcase_chart_Chart__void(/**@type {Object}*/ ($Casts.$to($Overlay.m_get__$devirt__jsinterop_base_JsPropertyMap__java_lang_String__java_lang_Object(Data.f_charts__org_patternfly_showcase_Data, 'donut'), Chart_$Overlay)));
  this.m_startExamples__void();
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('donut-basic', 'Basic', Code.m_code__java_lang_String__java_lang_String('donut-basic'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 230px; width: 230px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to(Donut.m_donut__org_patternfly_chart_donut_Donut().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('100'), Donut))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Pets'), Donut))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut chart example'), Donut))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Average number of pets'), Donut))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_donut_Donut([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Cats', 35), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Dogs', 55), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Birds', 10)]).m_labels__java_util_function_Function__org_patternfly_chart_donut_Donut(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data) =>{
    let data_1 = /**@type {Object}*/ ($Casts.$to(data, Data_$Overlay));
    return j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_1.x) + ': ' + data_1.y + '%';
   })))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('donut-ral', 'Right aligned legend', Code.m_code__java_lang_String__java_lang_String('donut-ral'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 230px; width: 350px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to(Donut.m_donut__org_patternfly_chart_donut_Donut().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('100'), Donut))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Pets'), Donut))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut chart example'), Donut))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Average number of pets'), Donut))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_donut_Donut([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Cats', 35), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Dogs', 55), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Birds', 10)]).m_labels__java_util_function_Function__org_patternfly_chart_donut_Donut(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_2) =>{
    let data_3 = /**@type {Object}*/ ($Casts.$to(data_2, Data_$Overlay));
    return j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_3.x) + ': ' + data_3.y + '%';
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Cats: 35', 'Dogs: 55', 'Birds: 10'], j_l_String))), Donut))).m_legendOrientation__org_patternfly_chart_LegendOrientation__org_jboss_elemento_TypedBuilder(LegendOrientation.f_vertical__org_patternfly_chart_LegendOrientation), Donut))).m_legendPosition__org_patternfly_chart_LegendPosition__org_jboss_elemento_TypedBuilder(LegendPosition.f_right__org_patternfly_chart_LegendPosition), Donut))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 140, 20, 20)), Donut))).m_width__int__org_jboss_elemento_TypedBuilder(350), Donut))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('donut-mc', 'Multi-color (ordered) with right aligned legend', Code.m_code__java_lang_String__java_lang_String('donut-mc'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 230px; width: 350px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to(Donut.m_donut__org_patternfly_chart_donut_Donut().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('100'), Donut))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Pets'), Donut))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut chart example'), Donut))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Average number of pets'), Donut))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_donut_Donut([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Cats', 35), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Dogs', 55), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Birds', 10)]).m_labels__java_util_function_Function__org_patternfly_chart_donut_Donut(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_4) =>{
    let data_5 = /**@type {Object}*/ ($Casts.$to(data_4, Data_$Overlay));
    return j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_5.x) + ': ' + data_5.y + '%';
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Cats: 35', 'Dogs: 55', 'Birds: 10'], j_l_String))), Donut))).m_legendOrientation__org_patternfly_chart_LegendOrientation__org_jboss_elemento_TypedBuilder(LegendOrientation.f_vertical__org_patternfly_chart_LegendOrientation), Donut))).m_legendPosition__org_patternfly_chart_LegendPosition__org_jboss_elemento_TypedBuilder(LegendPosition.f_right__org_patternfly_chart_LegendPosition), Donut))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 140, 20, 20)), Donut))).m_themeColor__org_patternfly_chart_ChartThemeColor__org_jboss_elemento_TypedBuilder(ChartThemeColor.f_multiOrdered__org_patternfly_chart_ChartThemeColor), Donut))).m_width__int__org_jboss_elemento_TypedBuilder(350), Donut))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('donut-bal', 'Bottom aligned legend', Code.m_code__java_lang_String__java_lang_String('donut-bal'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 275px; width: 300px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to(Donut.m_donut__org_patternfly_chart_donut_Donut().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('100'), Donut))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Pets'), Donut))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut chart example'), Donut))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Average number of pets'), Donut))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_donut_Donut([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Cats', 35), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Dogs', 55), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Birds', 10)]).m_labels__java_util_function_Function__org_patternfly_chart_donut_Donut(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_6) =>{
    let data_7 = /**@type {Object}*/ ($Casts.$to(data_6, Data_$Overlay));
    return j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_7.x) + ': ' + data_7.y + '%';
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Cats: 35', 'Dogs: 55', 'Birds: 10'], j_l_String))), Donut))).m_legendPosition__org_patternfly_chart_LegendPosition__org_jboss_elemento_TypedBuilder(LegendPosition.f_bottom__org_patternfly_chart_LegendPosition), Donut))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 20, 65, 20)), Donut))).m_height__int__org_jboss_elemento_TypedBuilder(275), Donut))).m_width__int__org_jboss_elemento_TypedBuilder(300), Donut))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('donut-small', 'Small', Code.m_code__java_lang_String__java_lang_String('donut-small'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 150px; width: 150px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to(Donut.m_donut__org_patternfly_chart_donut_Donut().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('100'), Donut))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Pets'), Donut))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut chart example'), Donut))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Average number of pets'), Donut))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_donut_Donut([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Cats', 35), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Dogs', 55), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Birds', 10)]).m_labels__java_util_function_Function__org_patternfly_chart_donut_Donut(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_8) =>{
    let data_9 = /**@type {Object}*/ ($Casts.$to(data_8, Data_$Overlay));
    return j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_9.x) + ': ' + data_9.y + '%';
   }))).m_height__int__org_jboss_elemento_TypedBuilder(150), Donut))).m_width__int__org_jboss_elemento_TypedBuilder(150), Donut))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('donut-small-ral', 'Small with right aligned legend', Code.m_code__java_lang_String__java_lang_String('donut-small-ral'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 150px; width: 275px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to(Donut.m_donut__org_patternfly_chart_donut_Donut().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('100'), Donut))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Pets'), Donut))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut chart example'), Donut))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Average number of pets'), Donut))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_donut_Donut([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Cats', 35), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Dogs', 55), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Birds', 10)]).m_labels__java_util_function_Function__org_patternfly_chart_donut_Donut(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_10) =>{
    let data_11 = /**@type {Object}*/ ($Casts.$to(data_10, Data_$Overlay));
    return j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_11.x) + ': ' + data_11.y + '%';
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Cats: 35', 'Dogs: 55', 'Birds: 10'], j_l_String))), Donut))).m_legendOrientation__org_patternfly_chart_LegendOrientation__org_jboss_elemento_TypedBuilder(LegendOrientation.f_vertical__org_patternfly_chart_LegendOrientation), Donut))).m_legendPosition__org_patternfly_chart_LegendPosition__org_jboss_elemento_TypedBuilder(LegendPosition.f_right__org_patternfly_chart_LegendPosition), Donut))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 145, 20, 20)), Donut))).m_height__int__org_jboss_elemento_TypedBuilder(150), Donut))).m_width__int__org_jboss_elemento_TypedBuilder(275), Donut))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('donut-small-bast', 'Small with bottom aligned subtitle', Code.m_code__java_lang_String__java_lang_String('donut-small-bast'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 165px; width: 275px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to(Donut.m_donut__org_patternfly_chart_donut_Donut().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('100'), Donut))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Pets'), Donut))).m_subTitlePosition__org_patternfly_chart_SubTitlePosition__org_jboss_elemento_TypedBuilder(SubTitlePosition.f_bottom__org_patternfly_chart_SubTitlePosition), Donut))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut chart example'), Donut))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Average number of pets'), Donut))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_donut_Donut([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Cats', 35), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Dogs', 55), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Birds', 10)]).m_labels__java_util_function_Function__org_patternfly_chart_donut_Donut(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_12) =>{
    let data_13 = /**@type {Object}*/ ($Casts.$to(data_12, Data_$Overlay));
    return j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_13.x) + ': ' + data_13.y + '%';
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Cats: 35', 'Dogs: 55', 'Birds: 10'], j_l_String))), Donut))).m_legendOrientation__org_patternfly_chart_LegendOrientation__org_jboss_elemento_TypedBuilder(LegendOrientation.f_vertical__org_patternfly_chart_LegendOrientation), Donut))).m_legendPosition__org_patternfly_chart_LegendPosition__org_jboss_elemento_TypedBuilder(LegendPosition.f_right__org_patternfly_chart_LegendPosition), Donut))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 145, 25, 20)), Donut))).m_height__int__org_jboss_elemento_TypedBuilder(165), Donut))).m_width__int__org_jboss_elemento_TypedBuilder(275), Donut))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('donut-small-rast', 'Small with right aligned subtitle', Code.m_code__java_lang_String__java_lang_String('donut-small-rast'), Supplier.$adapt(/**  @return {HTMLElement}*/ (() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to((/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('height: 200px; width: 300px;'), HTMLContainerBuilder))).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to((/**@type {Donut}*/ ($Casts.$to(Donut.m_donut__org_patternfly_chart_donut_Donut().m_title__java_lang_String__org_jboss_elemento_TypedBuilder('100'), Donut))).m_subTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Pets'), Donut))).m_subTitlePosition__org_patternfly_chart_SubTitlePosition__org_jboss_elemento_TypedBuilder(SubTitlePosition.f_right__org_patternfly_chart_SubTitlePosition), Donut))).m_ariaTitle__java_lang_String__org_jboss_elemento_TypedBuilder('Donut chart example'), Donut))).m_ariaDesc__java_lang_String__org_jboss_elemento_TypedBuilder('Average number of pets'), Donut))).m_data__arrayOf_org_patternfly_chart_Data__org_patternfly_chart_donut_Donut([Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Cats', 35), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Dogs', 55), Data_$Overlay.m_data__java_lang_String__double__org_patternfly_chart_Data('Birds', 10)]).m_labels__java_util_function_Function__org_patternfly_chart_donut_Donut(j_u_function_Function.$adapt(/**  @return {?string}*/ ((/** Object */ data_14) =>{
    let data_15 = /**@type {Object}*/ ($Casts.$to(data_14, Data_$Overlay));
    return j_l_String.m_valueOf__java_lang_Object__java_lang_String(data_15.x) + ': ' + data_15.y + '%';
   }))).m_legendData__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$stampType(['Cats: 35', 'Dogs: 55', 'Birds: 10'], j_l_String))), Donut))).m_legendPosition__org_patternfly_chart_LegendPosition__org_jboss_elemento_TypedBuilder(LegendPosition.f_bottom__org_patternfly_chart_LegendPosition), Donut))).m_padding__org_patternfly_chart_Padding__org_jboss_elemento_TypedBuilder(Padding_$Overlay.m_padding__double__double__double__double__org_patternfly_chart_Padding(20, 50, 70, 20)), Donut))).m_height__int__org_jboss_elemento_TypedBuilder(200), Donut))).m_width__int__org_jboss_elemento_TypedBuilder(300), Donut))), HTMLContainerBuilder))).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  }))));
  this.m_startApiDocs__java_lang_Class__void(Class.$get(Donut));
  this.m_addApiDoc__java_lang_Class__org_patternfly_showcase_ApiDoc_Type__void(Class.$get(Donut), Type.f_chart__org_patternfly_showcase_ApiDoc_Type);
 }
 /** @nodts */
 static $clinit() {
  DonutChart.$clinit = () =>{};
  DonutChart.$loadModules();
  SnippetPage.$clinit();
 }
 /** @nodts @return {boolean} */
 static $isInstance(/** ? */ instance) {
  return instance instanceof DonutChart;
 }
 
 /** @nodts */
 static $loadModules() {
  HTMLDivElement_$Overlay = goog.module.get('elemental2.dom.HTMLDivElement.$Overlay$impl');
  Class = goog.module.get('java.lang.Class$impl');
  j_l_String = goog.module.get('java.lang.String$impl');
  j_u_function_Function = goog.module.get('java.util.function.Function$impl');
  Supplier = goog.module.get('java.util.function.Supplier$impl');
  $Overlay = goog.module.get('jsinterop.base.JsPropertyMap.$Overlay$impl');
  Elements = goog.module.get('org.jboss.elemento.Elements$impl');
  HTMLContainerBuilder = goog.module.get('org.jboss.elemento.HTMLContainerBuilder$impl');
  ChartThemeColor = goog.module.get('org.patternfly.chart.ChartThemeColor$impl');
  Data_$Overlay = goog.module.get('org.patternfly.chart.Data.$Overlay$impl');
  LegendOrientation = goog.module.get('org.patternfly.chart.LegendOrientation$impl');
  LegendPosition = goog.module.get('org.patternfly.chart.LegendPosition$impl');
  Padding_$Overlay = goog.module.get('org.patternfly.chart.Padding.$Overlay$impl');
  SubTitlePosition = goog.module.get('org.patternfly.chart.SubTitlePosition$impl');
  Donut = goog.module.get('org.patternfly.chart.donut.Donut$impl');
  Type = goog.module.get('org.patternfly.showcase.ApiDoc.Type$impl');
  Code = goog.module.get('org.patternfly.showcase.Code$impl');
  Data = goog.module.get('org.patternfly.showcase.Data$impl');
  Snippet = goog.module.get('org.patternfly.showcase.Snippet$impl');
  Chart_$Overlay = goog.module.get('org.patternfly.showcase.chart.Chart.$Overlay$impl');
  $Arrays = goog.module.get('vmbootstrap.Arrays$impl');
  $Casts = goog.module.get('vmbootstrap.Casts$impl');
 }
}
$Util.$setClassMetadata(DonutChart, 'org.patternfly.showcase.chart.DonutChart');

exports = DonutChart;

//# sourceMappingURL=DonutChart.js.map
