goog.module('org.patternfly.icon.PredefinedIcon');

goog.require('elemental2.dom.AddEventListenerOptions.$Overlay');
goog.require('elemental2.dom.DomGlobal.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.EventTarget.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('java.lang.Class');
goog.require('java.lang.IllegalArgumentException');
goog.require('java.lang.Iterable');
goog.require('java.lang.Object');
goog.require('java.lang.String');
goog.require('java.util.function.Consumer');
goog.require('java.util.function.Supplier');
goog.require('javaemul.internal.Exceptions');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.ClassList');
goog.require('org.jboss.elemento.ElementAttributeMethods');
goog.require('org.jboss.elemento.ElementClassListMethods');
goog.require('org.jboss.elemento.ElementConsumerMethods');
goog.require('org.jboss.elemento.ElementEventMethods');
goog.require('org.jboss.elemento.ElementIdMethods');
goog.require('org.jboss.elemento.ElementQueryMethods');
goog.require('org.jboss.elemento.ElementTextMethods');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.Role');
goog.require('org.jboss.elemento.logger.Logger');
goog.require('org.jboss.elemento.svg.SVG');
goog.require('org.jboss.elemento.svg.SVGContainerBuilder');
goog.require('org.jboss.elemento.svg.SVGElement.$Overlay');
goog.require('org.jboss.elemento.svg.SVGElementDataMethods');
goog.require('org.jboss.elemento.svg.SVGElementStyleMethods');
goog.require('org.jboss.elemento.svg.SVGPathElement.$Overlay');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.core.Roles');
goog.require('org.patternfly.icon.IconSpec');
goog.require('org.patternfly.icon.IconSpecLookup');
goog.require('org.patternfly.style.Classes');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const PredefinedIcon = goog.require('org.patternfly.icon.PredefinedIcon$impl');
exports = PredefinedIcon;
