goog.module('org.patternfly.component.wizard.WizardNavItem');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.HTMLButtonElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLLIElement.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('java.lang.String');
goog.require('java.util.HashMap');
goog.require('java.util.Map');
goog.require('java.util.function.Supplier');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.ElementTextDelegate');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.ComponentIcon');
goog.require('org.patternfly.component.HasIdentifier');
goog.require('org.patternfly.component.ValidationStatus');
goog.require('org.patternfly.component.wizard.Wizard');
goog.require('org.patternfly.component.wizard.WizardSubComponent');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.ComponentContext');
goog.require('org.patternfly.icon.PredefinedIcon');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Modifiers.Disabled');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const WizardNavItem = goog.require('org.patternfly.component.wizard.WizardNavItem$impl');
exports = WizardNavItem;
