goog.module('org.patternfly.showcase.Snippet');

goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLAnchorElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('java.lang.Object');
goog.require('java.lang.String');
goog.require('java.util.function.Consumer');
goog.require('java.util.function.Supplier');
goog.require('jsinterop.base.JsPropertyMap.$Overlay');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.Id');
goog.require('org.jboss.elemento.IsElement');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.component.content.Content');
goog.require('org.patternfly.component.content.ContentType');
goog.require('org.patternfly.component.tooltip.Tooltip');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.extension.codeeditor.CodeEditor');
goog.require('org.patternfly.extension.codeeditor.CodeEditorAction');
goog.require('org.patternfly.extension.codeeditor.CodeEditorActions');
goog.require('org.patternfly.extension.codeeditor.CodeEditorHeader');
goog.require('org.patternfly.handler.ComponentHandler');
goog.require('org.patternfly.icon.IconSets.fas');
goog.require('org.patternfly.icon.IconSets.rhUi');
goog.require('org.patternfly.icon.PredefinedIcon');
goog.require('org.patternfly.layout.flex.AlignItems');
goog.require('org.patternfly.layout.flex.Flex');
goog.require('org.patternfly.layout.flex.SpaceItems');
goog.require('org.patternfly.layout.stack.Stack');
goog.require('org.patternfly.layout.stack.StackItem');
goog.require('org.patternfly.style.Classes');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const Snippet = goog.require('org.patternfly.showcase.Snippet$impl');
exports = Snippet;
