goog.module('org.patternfly.component.toolbar.ToolbarToggleGroup');

goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('java.lang.Iterable');
goog.require('java.lang.String');
goog.require('java.util.Iterator');
goog.require('java.util.LinkedHashMap');
goog.require('java.util.List');
goog.require('java.util.Map');
goog.require('java.util.Spliterator');
goog.require('java.util.function.BiConsumer');
goog.require('java.util.function.Consumer');
goog.require('java.util.function.Function');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.AddItemHandler');
goog.require('org.patternfly.component.AurHandler');
goog.require('org.patternfly.component.HasItems');
goog.require('org.patternfly.component.RemoveItemHandler');
goog.require('org.patternfly.component.UpdateItemHandler');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.component.divider.Divider');
goog.require('org.patternfly.component.divider.DividerType');
goog.require('org.patternfly.component.toolbar.ToolbarGroup');
goog.require('org.patternfly.component.toolbar.ToolbarItem');
goog.require('org.patternfly.component.toolbar.ToolbarSubComponent');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.icon.IconSets.rhUi');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Orientation');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const ToolbarToggleGroup = goog.require('org.patternfly.component.toolbar.ToolbarToggleGroup$impl');
exports = ToolbarToggleGroup;
